apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-html-app
  template:
    metadata:
      labels:
        app: my-html-app
    spec:
      containers:
      - name: nginx
        image: ahanan04/cicd-pipeline:latest  # This will be replaced by the CI/CD pipeline
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-html-app-service
spec:
  selector:
    app: my-html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer