apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-pipeline
  template:
    metadata:
      labels:
        app: cicd-pipeline
    spec:
      containers:
      - name: cicd-pipeline
        image: ahanan04/cicd-pipeline:$IMAGE_TAG  # Replace with your image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-pipeline-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cicd-pipeline